### ISSUE TITLE
Require Variable

### ISSUE THREAD

**Issue by CMCDragonkai** [hzlmn/xeon#1]
Does Xeon work with require variable? I suppose that may require actual execution if you allow arbitrary expressions. In that case, a limited pure expression like constexpr in C++ could be used.

Also one suggestion is to use `source` or `.` instead of a custom `require`. That way my scripts stay executable like a shell script, but I can bundle it if necessary.

**Comment by hzlmn** [comment]
@CMCDragonkai Not yet, but it is in progress. The reason why I use custom require and not sourcing file s is that xeon will provide same API for require things for each shell type and when I finish AST generator/stringifier it will construct your script whatever you want it - bundling to single file or sourcing and a lot other goodness that will come with AST. Its kind like babel for shell scripts I think 😄 .
Hope I crarified my point...

**Comment by CMCDragonkai** [comment]
Have you seen shellcheck? I reckon you'll need static analysis to actually compile things and do dead code elimination. I might have a large library of shell functions that I import to all my scripts, but they only use a subset of it. https://github.com/koalaman/shellcheck

**Comment by CMCDragonkai** [comment]
BTW, this kind of inclusion is similar to C's preprocessor macros. I've been using: https://github.com/iwonbigbro/bashpp to implement this type of compile time inclusion before I found your project. However it wouldn't be much more work to add in macros that are dependent on flags passed in command line.

Also this would be easier to deploy, if xeon can be packaged into a binary executable.

**Comment by hzlmn** [comment]
@CMCDragonkai  Yes, I know about shellcheck, It's ast builder what I actually need but it's Haskell that i am not strong in. I will contact this guy, maybe we could make something together.
Btw, dead code elimination could be done now by providing some export syntax, but as i currently do not have code analysis, it's not the best way to hardcode regexes :smile:

**Comment by CMCDragonkai** [comment]
Yea there's a problem with bash allowing arbitrary expressions to become function calls, and that would complicate finding function level dependencies, and allowing automatic dead code elimination. I'm not sure of a efficient solution to such an untyped language.

**Comment by CMCDragonkai** [comment]
Also bashpp has a serious bug that I reported a while back, see its issues. It hasn't been fixed yet.

**Comment by hzlmn** [comment]
Should be closed. Further discussions on gitter https://gitter.im/hzlmn/xeon if needed.
